[package]
name = "markov"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.12"
winit = "0.26"
env_logger = "0.9"
log = "0.4"
pollster = "0.2"
bytemuck = { version = "1.4", features = [ "derive" ] }
rand = "0.8.5"